### ISSUE TITLE
Ability to define a different range

### ISSUE THREAD

**Issue by hugopeek** [Sterc/reviews#2]
Although 1-5 is probably preferred in most cases, it would also be nice if you can use an alternative range like 1-10 for a rating.

**Comment by Oetzie** [comment]
@hugopeek There is a system setting `reviews.ratings` with a default value `1||5`. This is the min and max rating, so you can change it to `1||10` if you want.

**Comment by hugopeek** [comment]
Ah ok, sorry I missed that..
